version: '3.8'
services:
  db:
    image: postgres:17
    restart: always
    env_file:
      - backend/.env.prod
    environment:
      POSTGRES_USER: ${{ vars.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django-app:
    build: ./backend
    container_name: django-server
    image: django-app-backend
    env_file:
      - backend/.env.prod
    environment:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: ${{ vars.DEBUG }}
      DB_ENGINE: ${{ vars.DB_ENGINE }}
      DB_NAME: ${{ vars.POSTGRES_DB }}
      DB_USER: ${{ vars.POSTGRES_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/transactions/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - django-server:/app
      - static_volume:/app/staticfiles

  frontend:
    build: ./frontend
    container_name: react-frontend
    image: react-app-frontend
    env_file:
      - frontend/.env.production
    environment:
      NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}
      API_URL: ${{ vars.API_URL }}
    ports:
      - "3000:3000"
    volumes:
      - react-front:/app
    depends_on:
      - django-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - django-app


volumes:
  postgres_data:
  django-server:
  static_volume:
  react-front: